apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: hj5kk7nxo-java-quarkus 
  janus-idp.io/tekton: hj5kk7nxo-java-quarkus
  backstage.io/kubernetes-id: hj5kk7nxo-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hj5kk7nxo-java-quarkus
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml